export const MOCK_PATIENT = {
  id: "PT-2026-20847",
  name: "Eleanor Voss",
  dob: "1958-03-14",
  age: 66,
  eye: "Right Eye (OD)",
  examDate: "2026-02-18",
  referringPhysician: "Dr. A. Ramachandran, MD",
};

export const MOCK_RESULTS = {
  diagnosis: "Diabetic Retinopathy",
  icd10: "E11.3591",
  etdrsLevel: "Moderate NPDR",
  severity: 3,
  maxSeverity: 5,
  aiConfidence: 94.7,
  processingTime: "2.4s",
  modelVersion: "Opthalmic v1.0",
  recommendation:
    "Patient presents with moderate non-proliferative diabetic retinopathy (NPDR) with high AI confidence. Recommend follow-up ophthalmology consultation within 3–6 months. Consider pan-retinal photocoagulation (PRP) if progression to PDR is detected. Tight glycemic control (HbA1c < 7%) and blood pressure management are strongly advised.",
  clinicalFeatures: [
    {
      name: "Microaneurysms",
      value: "Present (>5)",
      unit: "",
      reference: "Absent",
      status: "elevated",
      score: 0.89,
    },
    {
      name: "Hard Exudates",
      value: "Moderate",
      unit: "",
      reference: "None",
      status: "warning",
      score: 0.72,
    },
    {
      name: "Hemorrhages",
      value: "Dot/Blot (3 quadrants)",
      unit: "",
      reference: "None",
      status: "elevated",
      score: 0.81,
    },
    {
      name: "Neovascularization",
      value: "Absent",
      unit: "",
      reference: "Absent",
      status: "normal",
      score: 0.04,
    },
    {
      name: "Vessel Tortuosity",
      value: "Mild Increase",
      unit: "",
      reference: "Normal",
      status: "warning",
      score: 0.58,
    },
    {
      name: "Disc-to-Cup Ratio",
      value: "0.42",
      unit: "ratio",
      reference: "0.3–0.5",
      status: "normal",
      score: 0.42,
    },
    {
      name: "Macular Edema",
      value: "Suspected",
      unit: "",
      reference: "None",
      status: "warning",
      score: 0.67,
    },
    {
      name: "Lens Opacity",
      value: "Grade 1",
      unit: "",
      reference: "Grade 0",
      status: "warning",
      score: 0.35,
    },
  ],
  dcaCurveData: [],
  severityStages: [
    { level: 1, label: "No DR", description: "No apparent diabetic retinopathy detected." },
    { level: 2, label: "Mild NPDR", description: "Microaneurysms only." },
    {
      level: 3,
      label: "Moderate NPDR",
      description: "More than microaneurysms but less than severe NPDR.",
      current: true,
    },
    {
      level: 4,
      label: "Severe NPDR",
      description: "Any of: 20+ intraretinal hemorrhages in all 4 quadrants.",
    },
    { level: 5, label: "PDR", description: "Neovascularization or vitreous/pre-retinal hemorrhage." },
  ],
};
